-- =============================================================================
-- WaxPrep v3.0 — Cognitive Memory Architecture Migration
-- =============================================================================
-- Architecture Decision: PostgreSQL-native graph layer
-- Rationale: Zero new infrastructure. Existing pgvector + JSONB handles
-- embeddings and flexible properties. Recursive CTEs provide traversal.
-- Neo4j adapter defined in code for future swap when query complexity grows.
-- =============================================================================

-- =============================================================================
-- BREAKTHROUGH 1: DUAL-PROCESS SESSION SEGMENTATION
-- =============================================================================

-- Segmentation configuration: learned weights and thresholds
-- student_id = NULL means global default; per-student rows override
CREATE TABLE IF NOT EXISTS segmentation_config (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT, -- NULL = global default
    weights JSONB NOT NULL DEFAULT '{
        "topic_drift": 0.35,
        "emotional": 0.25,
        "cognitive": 0.25,
        "time": 0.10,
        "pedagogical": 0.05
    }',
    thresholds JSONB NOT NULL DEFAULT '{
        "boundary": 0.6,
        "time_gap": 30,
        "system1_trigger": 0.3
    }',
    features JSONB NOT NULL DEFAULT '{
        "use_embedding_drift": true,
        "use_emotional_delta": true,
        "use_lexical_shift": true,
        "use_cognitive_task_detection": true,
        "use_pedagogical_transition": true
    }',
    model_config JSONB NOT NULL DEFAULT '{
        "system1_model_tier": "fast",
        "system2_model_tier": "smart"
    }',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(student_id)
);

CREATE INDEX IF NOT EXISTS idx_segmentation_config_student ON segmentation_config(student_id);

-- Session boundaries log (for learning and observability)
CREATE TABLE IF NOT EXISTS session_boundaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    previous_session_id TEXT,
    new_session_id TEXT NOT NULL,
    boundary_type TEXT NOT NULL, -- dynamically generated by LLM, not enum
    boundary_probability FLOAT NOT NULL,
    boundary_signals JSONB NOT NULL DEFAULT '{}',
    llm_reasoning TEXT,
    was_correct BOOLEAN, -- human feedback or post-hoc validation
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_boundaries_student ON session_boundaries(student_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_boundaries_type ON session_boundaries(boundary_type);

-- Extend existing sessions table with cognitive boundary fields
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'boundary_type') THEN
        ALTER TABLE sessions ADD COLUMN boundary_type TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'boundary_probability') THEN
        ALTER TABLE sessions ADD COLUMN boundary_probability FLOAT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'boundary_signals') THEN
        ALTER TABLE sessions ADD COLUMN boundary_signals JSONB NOT NULL DEFAULT '{}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'previous_session_id') THEN
        ALTER TABLE sessions ADD COLUMN previous_session_id TEXT REFERENCES sessions(session_id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'continuity_score') THEN
        ALTER TABLE sessions ADD COLUMN continuity_score FLOAT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'cognitive_metadata') THEN
        ALTER TABLE sessions ADD COLUMN cognitive_metadata JSONB NOT NULL DEFAULT '{}';
    END IF;
END $$;

-- Extend conversation_turns with cognitive signals
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversation_turns' AND column_name = 'emotional_valence') THEN
        ALTER TABLE conversation_turns ADD COLUMN emotional_valence FLOAT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversation_turns' AND column_name = 'cognitive_load_estimate') THEN
        ALTER TABLE conversation_turns ADD COLUMN cognitive_load_estimate INT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversation_turns' AND column_name = 'topic_drift_score') THEN
        ALTER TABLE conversation_turns ADD COLUMN topic_drift_score FLOAT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'conversation_turns' AND column_name = 'is_boundary_turn') THEN
        ALTER TABLE conversation_turns ADD COLUMN is_boundary_turn BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- =============================================================================
-- BREAKTHROUGH 2: TEMPORAL KNOWLEDGE GRAPH (PostgreSQL-native)
-- =============================================================================

-- Graph nodes: flexible labels, JSONB properties, vector embeddings, bi-temporal
CREATE TABLE IF NOT EXISTS cognitive_graph_nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    labels TEXT[] NOT NULL DEFAULT '{}', -- e.g., {'Episode', 'Concept'}
    properties JSONB NOT NULL DEFAULT '{}',
    embedding VECTOR(384), -- matches existing MiniLM dimension; configurable
    event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ingest_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    validity_window tstzrange, -- [valid_from, valid_to); NULL valid_to = currently valid
    student_id TEXT,
    source TEXT, -- e.g., 'whatsapp', 'tool_result', 'sleep_mode'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_graph_nodes_labels ON cognitive_graph_nodes USING GIN(labels);
CREATE INDEX IF NOT EXISTS idx_graph_nodes_properties ON cognitive_graph_nodes USING GIN(properties);
CREATE INDEX IF NOT EXISTS idx_graph_nodes_student ON cognitive_graph_nodes(student_id);
CREATE INDEX IF NOT EXISTS idx_graph_nodes_event_time ON cognitive_graph_nodes(event_time);
CREATE INDEX IF NOT EXISTS idx_graph_nodes_validity ON cognitive_graph_nodes USING GIST(validity_window);
CREATE INDEX IF NOT EXISTS idx_graph_nodes_embedding ON cognitive_graph_nodes USING ivfflat (embedding vector_cosine_ops);

-- Graph edges: typed relationships with properties and bi-temporal validity
CREATE TABLE IF NOT EXISTS cognitive_graph_edges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    target_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- e.g., 'EPISODIC_SEQUENTIAL', 'HAS_MASTERY'
    properties JSONB NOT NULL DEFAULT '{}',
    event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ingest_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    validity_window tstzrange,
    student_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_graph_edges_source ON cognitive_graph_edges(source_id);
CREATE INDEX IF NOT EXISTS idx_graph_edges_target ON cognitive_graph_edges(target_id);
CREATE INDEX IF NOT EXISTS idx_graph_edges_type ON cognitive_graph_edges(type);
CREATE INDEX IF NOT EXISTS idx_graph_edges_student ON cognitive_graph_edges(student_id);
CREATE INDEX IF NOT EXISTS idx_graph_edges_validity ON cognitive_graph_edges USING GIST(validity_window);

-- Node-edge lookup for fast traversal (materialized adjacency)
CREATE TABLE IF NOT EXISTS cognitive_graph_adjacency (
    node_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    edge_id UUID NOT NULL REFERENCES cognitive_graph_edges(id) ON DELETE CASCADE,
    direction TEXT NOT NULL CHECK (direction IN ('out', 'in')),
    neighbor_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    edge_type TEXT NOT NULL,
    PRIMARY KEY (node_id, edge_id, direction)
);

CREATE INDEX IF NOT EXISTS idx_adjacency_node ON cognitive_graph_adjacency(node_id);
CREATE INDEX IF NOT EXISTS idx_adjacency_neighbor ON cognitive_graph_adjacency(neighbor_id);
CREATE INDEX IF NOT EXISTS idx_adjacency_type ON cognitive_graph_adjacency(edge_type);

-- Graph node external references (link graph nodes to existing relational rows)
CREATE TABLE IF NOT EXISTS cognitive_graph_references (
    node_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    table_name TEXT NOT NULL,
    row_id TEXT NOT NULL,
    row_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (node_id, table_name, row_id)
);

CREATE INDEX IF NOT EXISTS idx_graph_refs_lookup ON cognitive_graph_references(table_name, row_id);

-- =============================================================================
-- BREAKTHROUGH 3: HUMAN-LIKE FORGETTING ENGINE
-- =============================================================================

-- Per-student forgetting parameters (learned over time)
CREATE TABLE IF NOT EXISTS forgetting_params (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL UNIQUE,
    decay_rate FLOAT NOT NULL DEFAULT 0.5,
    decay_temperature FLOAT NOT NULL DEFAULT 1.0,
    retrieval_threshold FLOAT NOT NULL DEFAULT 0.3,
    emotional_salience_weight FLOAT NOT NULL DEFAULT 1.5,
    contextual_boost_weight FLOAT NOT NULL DEFAULT 2.0,
    noise_stddev FLOAT NOT NULL DEFAULT 0.3,
    oblivion_threshold FLOAT NOT NULL DEFAULT 0.1,
    uncertainty_threshold FLOAT NOT NULL DEFAULT 0.4,
    top_k_retrieval INT NOT NULL DEFAULT 5,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_forgetting_params_student ON forgetting_params(student_id);

-- Memory access logs (for activation learning and feedback)
CREATE TABLE IF NOT EXISTS memory_access_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    memory_id TEXT NOT NULL, -- can reference graph node id or turn_id
    memory_type TEXT NOT NULL, -- 'graph_node', 'conversation_turn', 'fact'
    query TEXT,
    activation_score FLOAT,
    oblivion_probability FLOAT,
    was_retrieved BOOLEAN NOT NULL DEFAULT FALSE,
    retrieval_rank INT,
    feedback_score FLOAT DEFAULT 0, -- +1 if memory was useful, -1 if irrelevant
    accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_memory_access_student ON memory_access_logs(student_id, accessed_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_access_memory ON memory_access_logs(memory_id, memory_type);

-- =============================================================================
-- BREAKTHROUGH 4: PREDICTIVE MEMORY PRE-LOAD
-- =============================================================================

CREATE TABLE IF NOT EXISTS predictive_preloads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL UNIQUE,
    context JSONB NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    hit_count INT NOT NULL DEFAULT 0,
    miss_count INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_preloads_expires ON predictive_preloads(expires_at);

-- -- Forgetting curve tracking per concept (Ebbinghaus-inspired)
CREATE TABLE IF NOT EXISTS concept_retention_curves (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    concept_name TEXT NOT NULL,
    first_studied_at TIMESTAMPTZ NOT NULL,
    last_reviewed_at TIMESTAMPTZ,
    review_count INT NOT NULL DEFAULT 0,
    optimal_interval_hours FLOAT NOT NULL DEFAULT 24,
    retention_estimate FLOAT NOT NULL DEFAULT 1.0,
    decay_rate_observed FLOAT,
    next_predicted_review TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(student_id, concept_name)
);

CREATE INDEX IF NOT EXISTS idx_retention_student ON concept_retention_curves(student_id);
CREATE INDEX IF NOT EXISTS idx_retention_next_review ON concept_retention_curves(next_predicted_review);

-- =============================================================================
-- BREAKTHROUGH 5: MEMORY PALACE ORGANIZER
-- =============================================================================

-- Palace hierarchy: dynamically constructed per student
CREATE TABLE IF NOT EXISTS memory_palaces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL UNIQUE,
    palace_name TEXT NOT NULL DEFAULT 'Learning Universe',
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_palaces_student ON memory_palaces(student_id);

-- Palace hierarchy nodes (Wings, Rooms, Drawers)
CREATE TABLE IF NOT EXISTS memory_palace_nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    palace_id UUID NOT NULL REFERENCES memory_palaces(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES memory_palace_nodes(id) ON DELETE CASCADE,
    node_type TEXT NOT NULL CHECK (node_type IN ('wing', 'room', 'drawer')),
    name TEXT NOT NULL,
    domain TEXT, -- subject domain, e.g., 'mathematics', 'biology'
    topic TEXT,
    concept TEXT,
    metadata JSONB NOT NULL DEFAULT '{}',
    access_count INT NOT NULL DEFAULT 0,
    last_accessed TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_palace_nodes_palace ON memory_palace_nodes(palace_id);
CREATE INDEX IF NOT EXISTS idx_palace_nodes_parent ON memory_palace_nodes(parent_id);
CREATE INDEX IF NOT EXISTS idx_palace_nodes_type ON memory_palace_nodes(node_type);

-- Links between palace nodes and graph nodes (what lives where)
CREATE TABLE IF NOT EXISTS memory_palace_contents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    palace_node_id UUID NOT NULL REFERENCES memory_palace_nodes(id) ON DELETE CASCADE,
    graph_node_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    content_type TEXT NOT NULL, -- 'episode', 'fact', 'concept', 'mistake'
    placed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    access_count INT NOT NULL DEFAULT 0,
    last_accessed TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_palace_contents_node ON memory_palace_contents(palace_node_id);
CREATE INDEX IF NOT EXISTS idx_palace_contents_graph ON memory_palace_contents(graph_node_id);

-- Cross-domain tunnels (AI-discovered connections between palace nodes)
CREATE TABLE IF NOT EXISTS memory_palace_tunnels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    palace_id UUID NOT NULL REFERENCES memory_palaces(id) ON DELETE CASCADE,
    source_node_id UUID NOT NULL REFERENCES memory_palace_nodes(id) ON DELETE CASCADE,
    target_node_id UUID NOT NULL REFERENCES memory_palace_nodes(id) ON DELETE CASCADE,
    strength FLOAT NOT NULL DEFAULT 0.5,
    reasoning TEXT,
    discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_validated TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(source_node_id, target_node_id)
);

CREATE INDEX IF NOT EXISTS idx_palace_tunnels_palace ON memory_palace_tunnels(palace_id);
CREATE INDEX IF NOT EXISTS idx_palace_tunnels_active ON memory_palace_tunnels(is_active, strength DESC);

-- =============================================================================
-- BREAKTHROUGH 6: TOOL-MEMORY SYMBIOSIS
-- =============================================================================

-- Tool memory: per-tool, per-student performance and learning
CREATE TABLE IF NOT EXISTS tool_memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tool_name TEXT NOT NULL,
    student_id TEXT, -- NULL = global stats
    total_calls INT NOT NULL DEFAULT 0,
    successful_calls INT NOT NULL DEFAULT 0,
    failed_calls INT NOT NULL DEFAULT 0,
    avg_latency_ms FLOAT,
    optimal_params JSONB NOT NULL DEFAULT '{}',
    common_failures JSONB NOT NULL DEFAULT '[]',
    typical_use_cases JSONB NOT NULL DEFAULT '[]',
    dependency_chains JSONB NOT NULL DEFAULT '[]',
    last_used_at TIMESTAMPTZ,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tool_name, student_id)
);

CREATE INDEX IF NOT EXISTS idx_tool_memories_name ON tool_memories(tool_name);
CREATE INDEX IF NOT EXISTS idx_tool_memories_student ON tool_memories(student_id);

-- Tool call to memory link (every tool result becomes a graph node)
CREATE TABLE IF NOT EXISTS tool_call_memory_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tool_call_id TEXT NOT NULL,
    graph_node_id UUID NOT NULL REFERENCES cognitive_graph_nodes(id) ON DELETE CASCADE,
    link_type TEXT NOT NULL, -- 'produced', 'informed_by', 'corrected'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tool_call_links_tool ON tool_call_memory_links(tool_call_id);
CREATE INDEX IF NOT EXISTS idx_tool_call_links_node ON tool_call_memory_links(graph_node_id);

-- =============================================================================
-- BREAKTHROUGH 7: OFFLINE MEMORY CONSOLIDATION (SLEEP MODE)
-- =============================================================================

-- Sleep mode execution logs
CREATE TABLE IF NOT EXISTS consolidation_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    phase TEXT NOT NULL, -- dynamic, not enum: 'contradiction_detection', 'pattern_extraction', etc.
    items_processed INT,
    items_created INT,
    items_modified INT,
    items_archived INT,
    insights_generated JSONB,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_consolidation_logs_student ON consolidation_logs(student_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_consolidation_logs_phase ON consolidation_logs(phase);

-- Detected contradictions
CREATE TABLE IF NOT EXISTS memory_contradictions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    attribute_key TEXT NOT NULL,
    current_fact_node_id UUID REFERENCES cognitive_graph_nodes(id),
    outdated_fact_node_id UUID REFERENCES cognitive_graph_nodes(id),
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolution_type TEXT, -- 'superseded', 'merged', 'uncertain'
    confidence FLOAT NOT NULL DEFAULT 0.7
);

CREATE INDEX IF NOT EXISTS idx_contradictions_student ON memory_contradictions(student_id, detected_at DESC);

-- Extracted patterns (meta-cognitive insights)
CREATE TABLE IF NOT EXISTS memory_patterns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    pattern_name TEXT NOT NULL,
    description TEXT NOT NULL,
    evidence_episodes JSONB NOT NULL DEFAULT '[]',
    confidence FLOAT NOT NULL DEFAULT 0.5,
    category TEXT, -- 'learning', 'emotional', 'behavioral'
    first_detected TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_observed TIMESTAMPTZ,
    occurrence_count INT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_patterns_student ON memory_patterns(student_id, category);
CREATE INDEX IF NOT EXISTS idx_patterns_name ON memory_patterns(pattern_name);

-- Graph communities (Louvain or similar)
CREATE TABLE IF NOT EXISTS memory_communities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT NOT NULL,
    community_name TEXT,
    summary TEXT,
    member_count INT NOT NULL DEFAULT 0,
    member_node_ids UUID[] NOT NULL DEFAULT '{}',
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    llm_summary TEXT
);

CREATE INDEX IF NOT EXISTS idx_communities_student ON memory_communities(student_id);

-- =============================================================================
-- COGNITIVE CONFIGURATION TABLES
-- =============================================================================

-- Global cognitive system configuration
CREATE TABLE IF NOT EXISTS cognitive_system_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed default configurations
INSERT INTO cognitive_system_config (key, value, description) VALUES
('segmentation', '{"enabled": true, "system1_always": true, "system2_threshold": 0.3}', 'Session segmentation engine settings'),
('forgetting', '{"enabled": true, "default_decay_rate": 0.5, "default_decay_temperature": 1.0, "default_retrieval_threshold": 0.3}', 'Forgetting engine defaults'),
('prediction', '{"enabled": true, "preload_ttl_seconds": 21600, "prediction_horizon_days": 7}', 'Predictive pre-load settings'),
('palace', '{"enabled": true, "auto_construct": true, "max_wings": 20, "max_rooms_per_wing": 50}', 'Memory palace settings'),
('tool_memory', '{"enabled": true, "learn_from_failures": true, "dependency_tracking": true}', 'Tool-memory symbiosis settings'),
('sleep_mode', '{"enabled": true, "schedule_cron": "0 2 * * *", "timezone_aware": true, "max_students_per_night": 100}', 'Sleep mode consolidation settings'),
('graph', '{"adapter": "postgres", "neo4j_uri": null, "neo4j_user": null, "embedding_dimension": 384}', 'Graph database adapter configuration')
ON CONFLICT (key) DO NOTHING;

-- Seed global segmentation config
INSERT INTO segmentation_config (student_id, weights, thresholds, features, model_config)
VALUES (
    NULL,
    '{"topic_drift": 0.35, "emotional": 0.25, "cognitive": 0.25, "time": 0.10, "pedagogical": 0.05}',
    '{"boundary": 0.6, "time_gap": 30, "system1_trigger": 0.3}',
    '{"use_embedding_drift": true, "use_emotional_delta": true, "use_lexical_shift": true, "use_cognitive_task_detection": true, "use_pedagogical_transition": true}',
    '{"system1_model_tier": "fast", "system2_model_tier": "smart"}'
)
ON CONFLICT (student_id) DO NOTHING;

-- =============================================================================
-- END OF COGNITIVE MEMORY ARCHITECTURE MIGRATION
-- =============================================================================